/*
 * This file is generated by jOOQ.
 */
package net.rupyber_studios.rupyber_database_api.jooq;


import java.util.Arrays;
import java.util.List;

import net.rupyber_studios.rupyber_database_api.jooq.tables.EmergencyCallNumbersTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.EmergencyCallsTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentNumbersTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentPlayersTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentTypesTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentsTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.PlayersTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.PrioritiesTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.RanksTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.RecipientsTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.ResponseCodesTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.RolesTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.StatusLogsTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.StatusesTable;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>EmergencyCallNumbers</code>.
     */
    public final EmergencyCallNumbersTable EmergencyCallNumbers = EmergencyCallNumbersTable.EmergencyCallNumbers;

    /**
     * The table <code>EmergencyCalls</code>.
     */
    public final EmergencyCallsTable EmergencyCalls = EmergencyCallsTable.EmergencyCalls;

    /**
     * The table <code>IncidentNumbers</code>.
     */
    public final IncidentNumbersTable IncidentNumbers = IncidentNumbersTable.IncidentNumbers;

    /**
     * The table <code>IncidentPlayers</code>.
     */
    public final IncidentPlayersTable IncidentPlayers = IncidentPlayersTable.IncidentPlayers;

    /**
     * The table <code>Incidents</code>.
     */
    public final IncidentsTable Incidents = IncidentsTable.Incidents;

    /**
     * The table <code>IncidentTypes</code>.
     */
    public final IncidentTypesTable IncidentTypes = IncidentTypesTable.IncidentTypes;

    /**
     * The table <code>Players</code>.
     */
    public final PlayersTable Players = PlayersTable.Players;

    /**
     * The table <code>Priorities</code>.
     */
    public final PrioritiesTable Priorities = PrioritiesTable.Priorities;

    /**
     * The table <code>Ranks</code>.
     */
    public final RanksTable Ranks = RanksTable.Ranks;

    /**
     * The table <code>Recipients</code>.
     */
    public final RecipientsTable Recipients = RecipientsTable.Recipients;

    /**
     * The table <code>ResponseCodes</code>.
     */
    public final ResponseCodesTable ResponseCodes = ResponseCodesTable.ResponseCodes;

    /**
     * The table <code>Roles</code>.
     */
    public final RolesTable Roles = RolesTable.Roles;

    /**
     * The table <code>Statuses</code>.
     */
    public final StatusesTable Statuses = StatusesTable.Statuses;

    /**
     * The table <code>StatusLogs</code>.
     */
    public final StatusLogsTable StatusLogs = StatusLogsTable.StatusLogs;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            EmergencyCallNumbersTable.EmergencyCallNumbers,
            EmergencyCallsTable.EmergencyCalls,
            IncidentNumbersTable.IncidentNumbers,
            IncidentPlayersTable.IncidentPlayers,
            IncidentsTable.Incidents,
            IncidentTypesTable.IncidentTypes,
            PlayersTable.Players,
            PrioritiesTable.Priorities,
            RanksTable.Ranks,
            RecipientsTable.Recipients,
            ResponseCodesTable.ResponseCodes,
            RolesTable.Roles,
            StatusesTable.Statuses,
            StatusLogsTable.StatusLogs
        );
    }
}
