/*
 * This file is generated by jOOQ.
 */
package net.rupyber_studios.rupyber_database_api.jooq;


import net.rupyber_studios.rupyber_database_api.jooq.tables.EmergencyCallNumbersTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.EmergencyCallsTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentNumbersTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentPlayersTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentTypesTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentsTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.PlayersTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.PrioritiesTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.RanksTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.RecipientsTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.ResponseCodesTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.RolesTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.StatusLogsTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.StatusesTable;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>EmergencyCallNumbers</code>.
     */
    public static final EmergencyCallNumbersTable EmergencyCallNumbers = EmergencyCallNumbersTable.EmergencyCallNumbers;

    /**
     * The table <code>EmergencyCalls</code>.
     */
    public static final EmergencyCallsTable EmergencyCalls = EmergencyCallsTable.EmergencyCalls;

    /**
     * The table <code>IncidentNumbers</code>.
     */
    public static final IncidentNumbersTable IncidentNumbers = IncidentNumbersTable.IncidentNumbers;

    /**
     * The table <code>IncidentPlayers</code>.
     */
    public static final IncidentPlayersTable IncidentPlayers = IncidentPlayersTable.IncidentPlayers;

    /**
     * The table <code>Incidents</code>.
     */
    public static final IncidentsTable Incidents = IncidentsTable.Incidents;

    /**
     * The table <code>IncidentTypes</code>.
     */
    public static final IncidentTypesTable IncidentTypes = IncidentTypesTable.IncidentTypes;

    /**
     * The table <code>Players</code>.
     */
    public static final PlayersTable Players = PlayersTable.Players;

    /**
     * The table <code>Priorities</code>.
     */
    public static final PrioritiesTable Priorities = PrioritiesTable.Priorities;

    /**
     * The table <code>Ranks</code>.
     */
    public static final RanksTable Ranks = RanksTable.Ranks;

    /**
     * The table <code>Recipients</code>.
     */
    public static final RecipientsTable Recipients = RecipientsTable.Recipients;

    /**
     * The table <code>ResponseCodes</code>.
     */
    public static final ResponseCodesTable ResponseCodes = ResponseCodesTable.ResponseCodes;

    /**
     * The table <code>Roles</code>.
     */
    public static final RolesTable Roles = RolesTable.Roles;

    /**
     * The table <code>Statuses</code>.
     */
    public static final StatusesTable Statuses = StatusesTable.Statuses;

    /**
     * The table <code>StatusLogs</code>.
     */
    public static final StatusLogsTable StatusLogs = StatusLogsTable.StatusLogs;
}
