/*
 * This file is generated by jOOQ.
 */
package net.rupyber_studios.rupyber_database_api.jooq;


import net.rupyber_studios.rupyber_database_api.jooq.tables.EmergencyCallNumbersTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.EmergencyCallsTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentNumbersTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentPlayersTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentTypesTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentsTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.PlayersTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.RanksTable;
import net.rupyber_studios.rupyber_database_api.jooq.tables.ResponseCodesTable;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>EmergencyCallNumbers</code>.
     */
    public static final EmergencyCallNumbersTable EmergencyCallNumbers = EmergencyCallNumbersTable.EmergencyCallNumbers;

    /**
     * The table <code>EmergencyCalls</code>.
     */
    public static final EmergencyCallsTable EmergencyCalls = EmergencyCallsTable.EmergencyCalls;

    /**
     * The table <code>IncidentNumbers</code>.
     */
    public static final IncidentNumbersTable IncidentNumbers = IncidentNumbersTable.IncidentNumbers;

    /**
     * The table <code>IncidentPlayers</code>.
     */
    public static final IncidentPlayersTable IncidentPlayers = IncidentPlayersTable.IncidentPlayers;

    /**
     * The table <code>Incidents</code>.
     */
    public static final IncidentsTable Incidents = IncidentsTable.Incidents;

    /**
     * The table <code>IncidentTypes</code>.
     */
    public static final IncidentTypesTable IncidentTypes = IncidentTypesTable.IncidentTypes;

    /**
     * The table <code>Players</code>.
     */
    public static final PlayersTable Players = PlayersTable.Players;

    /**
     * The table <code>Ranks</code>.
     */
    public static final RanksTable Ranks = RanksTable.Ranks;

    /**
     * The table <code>ResponseCodes</code>.
     */
    public static final ResponseCodesTable ResponseCodes = ResponseCodesTable.ResponseCodes;
}
