/*
 * This file is generated by jOOQ.
 */
package net.rupyber_studios.rupyber_database_api.jooq.tables.records;


import java.time.LocalDate;

import net.rupyber_studios.rupyber_database_api.jooq.tables.EmergencyCallNumbersTable;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmergencyCallNumbersRecord extends UpdatableRecordImpl<EmergencyCallNumbersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>EmergencyCallNumbers.day</code>.
     */
    public void setDay(LocalDate value) {
        set(0, value);
    }

    /**
     * Getter for <code>EmergencyCallNumbers.day</code>.
     */
    public LocalDate getDay() {
        return (LocalDate) get(0);
    }

    /**
     * Setter for <code>EmergencyCallNumbers.number</code>.
     */
    public void setNumber(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>EmergencyCallNumbers.number</code>.
     */
    public Integer getNumber() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<LocalDate> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmergencyCallNumbersRecord
     */
    public EmergencyCallNumbersRecord() {
        super(EmergencyCallNumbersTable.EmergencyCallNumbers);
    }

    /**
     * Create a detached, initialised EmergencyCallNumbersRecord
     */
    public EmergencyCallNumbersRecord(LocalDate day, Integer number) {
        super(EmergencyCallNumbersTable.EmergencyCallNumbers);

        setDay(day);
        setNumber(number);
        resetChangedOnNotNull();
    }
}
