/*
 * This file is generated by jOOQ.
 */
package net.rupyber_studios.rupyber_database_api.jooq.tables.records;


import java.time.LocalDateTime;

import net.rupyber_studios.rupyber_database_api.jooq.tables.EmergencyCallsTable;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmergencyCallsRecord extends UpdatableRecordImpl<EmergencyCallsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>EmergencyCalls.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>EmergencyCalls.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>EmergencyCalls.callNumber</code>.
     */
    public void setCallnumber(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>EmergencyCalls.callNumber</code>.
     */
    public Integer getCallnumber() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>EmergencyCalls.locationX</code>.
     */
    public void setLocationx(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>EmergencyCalls.locationX</code>.
     */
    public Integer getLocationx() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>EmergencyCalls.locationY</code>.
     */
    public void setLocationy(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>EmergencyCalls.locationY</code>.
     */
    public Integer getLocationy() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>EmergencyCalls.locationZ</code>.
     */
    public void setLocationz(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>EmergencyCalls.locationZ</code>.
     */
    public Integer getLocationz() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>EmergencyCalls.createdAt</code>.
     */
    public void setCreatedat(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>EmergencyCalls.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>EmergencyCalls.callerId</code>.
     */
    public void setCallerid(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>EmergencyCalls.callerId</code>.
     */
    public Integer getCallerid() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>EmergencyCalls.responderId</code>.
     */
    public void setResponderid(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>EmergencyCalls.responderId</code>.
     */
    public Integer getResponderid() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>EmergencyCalls.closedAt</code>.
     */
    public void setClosedat(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>EmergencyCalls.closedAt</code>.
     */
    public LocalDateTime getClosedat() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>EmergencyCalls.description</code>.
     */
    public void setDescription(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>EmergencyCalls.description</code>.
     */
    public String getDescription() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmergencyCallsRecord
     */
    public EmergencyCallsRecord() {
        super(EmergencyCallsTable.EmergencyCalls);
    }

    /**
     * Create a detached, initialised EmergencyCallsRecord
     */
    public EmergencyCallsRecord(Integer id, Integer callnumber, Integer locationx, Integer locationy, Integer locationz, LocalDateTime createdat, Integer callerid, Integer responderid, LocalDateTime closedat, String description) {
        super(EmergencyCallsTable.EmergencyCalls);

        setId(id);
        setCallnumber(callnumber);
        setLocationx(locationx);
        setLocationy(locationy);
        setLocationz(locationz);
        setCreatedat(createdat);
        setCallerid(callerid);
        setResponderid(responderid);
        setClosedat(closedat);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
