/*
 * This file is generated by jOOQ.
 */
package net.rupyber_studios.rupyber_database_api.jooq.tables.records;


import java.time.LocalDateTime;

import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentPlayersTable;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IncidentPlayersRecord extends TableRecordImpl<IncidentPlayersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>IncidentPlayers.incidentId</code>.
     */
    public void setIncidentid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>IncidentPlayers.incidentId</code>.
     */
    public Integer getIncidentid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>IncidentPlayers.roleId</code>.
     */
    public void setRoleid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>IncidentPlayers.roleId</code>.
     */
    public Integer getRoleid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>IncidentPlayers.playerId</code>.
     */
    public void setPlayerid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>IncidentPlayers.playerId</code>.
     */
    public Integer getPlayerid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>IncidentPlayers.addedAt</code>.
     */
    public void setAddedat(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>IncidentPlayers.addedAt</code>.
     */
    public LocalDateTime getAddedat() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>IncidentPlayers.removedAt</code>.
     */
    public void setRemovedat(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>IncidentPlayers.removedAt</code>.
     */
    public LocalDateTime getRemovedat() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IncidentPlayersRecord
     */
    public IncidentPlayersRecord() {
        super(IncidentPlayersTable.IncidentPlayers);
    }

    /**
     * Create a detached, initialised IncidentPlayersRecord
     */
    public IncidentPlayersRecord(Integer incidentid, Integer roleid, Integer playerid, LocalDateTime addedat, LocalDateTime removedat) {
        super(IncidentPlayersTable.IncidentPlayers);

        setIncidentid(incidentid);
        setRoleid(roleid);
        setPlayerid(playerid);
        setAddedat(addedat);
        setRemovedat(removedat);
        resetChangedOnNotNull();
    }
}
