/*
 * This file is generated by jOOQ.
 */
package net.rupyber_studios.rupyber_database_api.jooq.tables.records;


import java.time.LocalDateTime;

import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentsTable;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IncidentsRecord extends UpdatableRecordImpl<IncidentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Incidents.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Incidents.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Incidents.incidentNumber</code>.
     */
    public void setIncidentnumber(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Incidents.incidentNumber</code>.
     */
    public Integer getIncidentnumber() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>Incidents.emergencyCallId</code>.
     */
    public void setEmergencycallid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Incidents.emergencyCallId</code>.
     */
    public Integer getEmergencycallid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>Incidents.priority</code>.
     */
    public void setPriority(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>Incidents.priority</code>.
     */
    public Integer getPriority() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>Incidents.responseCodeId</code>.
     */
    public void setResponsecodeid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>Incidents.responseCodeId</code>.
     */
    public Integer getResponsecodeid() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>Incidents.recipients</code>.
     */
    public void setRecipients(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>Incidents.recipients</code>.
     */
    public Integer getRecipients() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>Incidents.incidentTypeId</code>.
     */
    public void setIncidenttypeid(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>Incidents.incidentTypeId</code>.
     */
    public Integer getIncidenttypeid() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>Incidents.locationX</code>.
     */
    public void setLocationx(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>Incidents.locationX</code>.
     */
    public Integer getLocationx() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>Incidents.locationY</code>.
     */
    public void setLocationy(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>Incidents.locationY</code>.
     */
    public Integer getLocationy() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>Incidents.locationZ</code>.
     */
    public void setLocationz(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>Incidents.locationZ</code>.
     */
    public Integer getLocationz() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>Incidents.description</code>.
     */
    public void setDescription(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>Incidents.description</code>.
     */
    public String getDescription() {
        return (String) get(10);
    }

    /**
     * Setter for <code>Incidents.createdAt</code>.
     */
    public void setCreatedat(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>Incidents.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>Incidents.createdBy</code>.
     */
    public void setCreatedby(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>Incidents.createdBy</code>.
     */
    public Integer getCreatedby() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>Incidents.closedAt</code>.
     */
    public void setClosedat(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>Incidents.closedAt</code>.
     */
    public LocalDateTime getClosedat() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>Incidents.closedBy</code>.
     */
    public void setClosedby(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>Incidents.closedBy</code>.
     */
    public Integer getClosedby() {
        return (Integer) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IncidentsRecord
     */
    public IncidentsRecord() {
        super(IncidentsTable.Incidents);
    }

    /**
     * Create a detached, initialised IncidentsRecord
     */
    public IncidentsRecord(Integer id, Integer incidentnumber, Integer emergencycallid, Integer priority, Integer responsecodeid, Integer recipients, Integer incidenttypeid, Integer locationx, Integer locationy, Integer locationz, String description, LocalDateTime createdat, Integer createdby, LocalDateTime closedat, Integer closedby) {
        super(IncidentsTable.Incidents);

        setId(id);
        setIncidentnumber(incidentnumber);
        setEmergencycallid(emergencycallid);
        setPriority(priority);
        setResponsecodeid(responsecodeid);
        setRecipients(recipients);
        setIncidenttypeid(incidenttypeid);
        setLocationx(locationx);
        setLocationy(locationy);
        setLocationz(locationz);
        setDescription(description);
        setCreatedat(createdat);
        setCreatedby(createdby);
        setClosedat(closedat);
        setClosedby(closedby);
        resetChangedOnNotNull();
    }
}
