/*
 * This file is generated by jOOQ.
 */
package net.rupyber_studios.rupyber_database_api.jooq.tables.records;


import net.rupyber_studios.rupyber_database_api.jooq.tables.RanksTable;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RanksRecord extends UpdatableRecordImpl<RanksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Ranks.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Ranks.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Ranks.rank</code>.
     */
    public void setRank(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Ranks.rank</code>.
     */
    public String getRank() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Ranks.color</code>.
     */
    public void setColor(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Ranks.color</code>.
     */
    public Integer getColor() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>Ranks.emergencyOperator</code>.
     */
    public void setEmergencyoperator(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>Ranks.emergencyOperator</code>.
     */
    public Boolean getEmergencyoperator() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RanksRecord
     */
    public RanksRecord() {
        super(RanksTable.Ranks);
    }

    /**
     * Create a detached, initialised RanksRecord
     */
    public RanksRecord(Integer id, String rank, Integer color, Boolean emergencyoperator) {
        super(RanksTable.Ranks);

        setId(id);
        setRank(rank);
        setColor(color);
        setEmergencyoperator(emergencyoperator);
        resetChangedOnNotNull();
    }
}
