/*
 * This file is generated by jOOQ.
 */
package net.rupyber_studios.rupyber_database_api.jooq.tables.records;


import net.rupyber_studios.rupyber_database_api.jooq.tables.RecipientsTable;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipientsRecord extends UpdatableRecordImpl<RecipientsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Recipients.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Recipients.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Recipients.recipients</code>.
     */
    public void setRecipients(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Recipients.recipients</code>.
     */
    public String getRecipients() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Recipients.color</code>.
     */
    public void setColor(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Recipients.color</code>.
     */
    public Integer getColor() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecipientsRecord
     */
    public RecipientsRecord() {
        super(RecipientsTable.Recipients);
    }

    /**
     * Create a detached, initialised RecipientsRecord
     */
    public RecipientsRecord(Integer id, String recipients, Integer color) {
        super(RecipientsTable.Recipients);

        setId(id);
        setRecipients(recipients);
        setColor(color);
        resetChangedOnNotNull();
    }
}
