/*
 * This file is generated by jOOQ.
 */
package net.rupyber_studios.rupyber_database_api.jooq.tables.records;


import net.rupyber_studios.rupyber_database_api.jooq.tables.ResponseCodesTable;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResponseCodesRecord extends UpdatableRecordImpl<ResponseCodesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ResponseCodes.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ResponseCodes.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ResponseCodes.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ResponseCodes.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ResponseCodes.color</code>.
     */
    public void setColor(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>ResponseCodes.color</code>.
     */
    public Integer getColor() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>ResponseCodes.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ResponseCodes.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResponseCodesRecord
     */
    public ResponseCodesRecord() {
        super(ResponseCodesTable.ResponseCodes);
    }

    /**
     * Create a detached, initialised ResponseCodesRecord
     */
    public ResponseCodesRecord(Integer id, String code, Integer color, String description) {
        super(ResponseCodesTable.ResponseCodes);

        setId(id);
        setCode(code);
        setColor(color);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
