/*
 * This file is generated by jOOQ.
 */
package net.rupyber_studios.rupyber_database_api.jooq.tables.records;


import java.time.LocalDateTime;

import net.rupyber_studios.rupyber_database_api.jooq.tables.StatusLogsTable;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusLogsRecord extends UpdatableRecordImpl<StatusLogsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>StatusLogs.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>StatusLogs.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>StatusLogs.playerId</code>.
     */
    public void setPlayerid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>StatusLogs.playerId</code>.
     */
    public Integer getPlayerid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>StatusLogs.statusId</code>.
     */
    public void setStatusid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>StatusLogs.statusId</code>.
     */
    public Integer getStatusid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>StatusLogs.changedAt</code>.
     */
    public void setChangedat(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>StatusLogs.changedAt</code>.
     */
    public LocalDateTime getChangedat() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StatusLogsRecord
     */
    public StatusLogsRecord() {
        super(StatusLogsTable.StatusLogs);
    }

    /**
     * Create a detached, initialised StatusLogsRecord
     */
    public StatusLogsRecord(Integer id, Integer playerid, Integer statusid, LocalDateTime changedat) {
        super(StatusLogsTable.StatusLogs);

        setId(id);
        setPlayerid(playerid);
        setStatusid(statusid);
        setChangedat(changedat);
        resetChangedOnNotNull();
    }
}
