/*
 * This file is generated by jOOQ.
 */
package net.rupyber_studios.rupyber_database_api.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import net.rupyber_studios.rupyber_database_api.jooq.DefaultSchema;
import net.rupyber_studios.rupyber_database_api.jooq.Keys;
import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentsTable.Incidents;
import net.rupyber_studios.rupyber_database_api.jooq.tables.PlayersTable.Players;
import net.rupyber_studios.rupyber_database_api.jooq.tables.records.EmergencyCallsRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmergencyCallsTable extends TableImpl<EmergencyCallsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>EmergencyCalls</code>
     */
    public static final EmergencyCallsTable EmergencyCalls = new EmergencyCallsTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmergencyCallsRecord> getRecordType() {
        return EmergencyCallsRecord.class;
    }

    /**
     * The column <code>EmergencyCalls.id</code>.
     */
    public final TableField<EmergencyCallsRecord, Integer> id = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>EmergencyCalls.callNumber</code>.
     */
    public final TableField<EmergencyCallsRecord, Integer> callNumber = createField(DSL.name("callNumber"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>EmergencyCalls.locationX</code>.
     */
    public final TableField<EmergencyCallsRecord, Integer> locationX = createField(DSL.name("locationX"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>EmergencyCalls.locationY</code>.
     */
    public final TableField<EmergencyCallsRecord, Integer> locationY = createField(DSL.name("locationY"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>EmergencyCalls.locationZ</code>.
     */
    public final TableField<EmergencyCallsRecord, Integer> locationZ = createField(DSL.name("locationZ"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>EmergencyCalls.createdAt</code>.
     */
    public final TableField<EmergencyCallsRecord, LocalDateTime> createdAt = createField(DSL.name("createdAt"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>EmergencyCalls.callerId</code>.
     */
    public final TableField<EmergencyCallsRecord, Integer> callerId = createField(DSL.name("callerId"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>EmergencyCalls.responderId</code>.
     */
    public final TableField<EmergencyCallsRecord, Integer> responderId = createField(DSL.name("responderId"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>EmergencyCalls.closedAt</code>.
     */
    public final TableField<EmergencyCallsRecord, LocalDateTime> closedAt = createField(DSL.name("closedAt"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>EmergencyCalls.description</code>.
     */
    public final TableField<EmergencyCallsRecord, String> description = createField(DSL.name("description"), SQLDataType.VARCHAR(256), this, "");

    private EmergencyCallsTable(Name alias, Table<EmergencyCallsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EmergencyCallsTable(Name alias, Table<EmergencyCallsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>EmergencyCalls</code> table reference
     */
    public EmergencyCallsTable(String alias) {
        this(DSL.name(alias), EmergencyCalls);
    }

    /**
     * Create an aliased <code>EmergencyCalls</code> table reference
     */
    public EmergencyCallsTable(Name alias) {
        this(alias, EmergencyCalls);
    }

    /**
     * Create a <code>EmergencyCalls</code> table reference
     */
    public EmergencyCallsTable() {
        this(DSL.name("EmergencyCalls"), null);
    }

    public <O extends Record> EmergencyCallsTable(Table<O> path, ForeignKey<O, EmergencyCallsRecord> childPath, InverseForeignKey<O, EmergencyCallsRecord> parentPath) {
        super(path, childPath, parentPath, EmergencyCalls);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EmergencyCalls extends EmergencyCallsTable implements Path<EmergencyCallsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EmergencyCalls(Table<O> path, ForeignKey<O, EmergencyCallsRecord> childPath, InverseForeignKey<O, EmergencyCallsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EmergencyCalls(Name alias, Table<EmergencyCallsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EmergencyCalls as(String alias) {
            return new EmergencyCalls(DSL.name(alias), this);
        }

        @Override
        public EmergencyCalls as(Name alias) {
            return new EmergencyCalls(alias, this);
        }

        @Override
        public EmergencyCalls as(Table<?> alias) {
            return new EmergencyCalls(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<EmergencyCallsRecord> getPrimaryKey() {
        return Keys.pk_EmergencyCalls;
    }

    @Override
    public List<ForeignKey<EmergencyCallsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.fk_EmergencyCalls_pk_Players);
    }

    private transient Players _players;

    /**
     * Get the implicit join path to the <code>Players</code> table.
     */
    public Players players() {
        if (_players == null)
            _players = new Players(this, Keys.fk_EmergencyCalls_pk_Players, null);

        return _players;
    }

    private transient Incidents _incidents;

    /**
     * Get the implicit to-many join path to the <code>Incidents</code> table
     */
    public Incidents incidents() {
        if (_incidents == null)
            _incidents = new Incidents(this, null, Keys.fk_Incidents_pk_EmergencyCalls.getInverseKey());

        return _incidents;
    }

    @Override
    public EmergencyCallsTable as(String alias) {
        return new EmergencyCallsTable(DSL.name(alias), this);
    }

    @Override
    public EmergencyCallsTable as(Name alias) {
        return new EmergencyCallsTable(alias, this);
    }

    @Override
    public EmergencyCallsTable as(Table<?> alias) {
        return new EmergencyCallsTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmergencyCallsTable rename(String name) {
        return new EmergencyCallsTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmergencyCallsTable rename(Name name) {
        return new EmergencyCallsTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmergencyCallsTable rename(Table<?> name) {
        return new EmergencyCallsTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmergencyCallsTable where(Condition condition) {
        return new EmergencyCallsTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmergencyCallsTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmergencyCallsTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmergencyCallsTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmergencyCallsTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmergencyCallsTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmergencyCallsTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmergencyCallsTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmergencyCallsTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmergencyCallsTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
