/*
 * This file is generated by jOOQ.
 */
package net.rupyber_studios.rupyber_database_api.jooq.tables;


import java.time.LocalDate;
import java.util.Collection;

import net.rupyber_studios.rupyber_database_api.jooq.DefaultSchema;
import net.rupyber_studios.rupyber_database_api.jooq.Keys;
import net.rupyber_studios.rupyber_database_api.jooq.tables.records.IncidentNumbersRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IncidentNumbersTable extends TableImpl<IncidentNumbersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>IncidentNumbers</code>
     */
    public static final IncidentNumbersTable IncidentNumbers = new IncidentNumbersTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IncidentNumbersRecord> getRecordType() {
        return IncidentNumbersRecord.class;
    }

    /**
     * The column <code>IncidentNumbers.day</code>.
     */
    public final TableField<IncidentNumbersRecord, LocalDate> day = createField(DSL.name("day"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>IncidentNumbers.number</code>.
     */
    public final TableField<IncidentNumbersRecord, Integer> number = createField(DSL.name("number"), SQLDataType.INTEGER.nullable(false), this, "");

    private IncidentNumbersTable(Name alias, Table<IncidentNumbersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IncidentNumbersTable(Name alias, Table<IncidentNumbersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>IncidentNumbers</code> table reference
     */
    public IncidentNumbersTable(String alias) {
        this(DSL.name(alias), IncidentNumbers);
    }

    /**
     * Create an aliased <code>IncidentNumbers</code> table reference
     */
    public IncidentNumbersTable(Name alias) {
        this(alias, IncidentNumbers);
    }

    /**
     * Create a <code>IncidentNumbers</code> table reference
     */
    public IncidentNumbersTable() {
        this(DSL.name("IncidentNumbers"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<IncidentNumbersRecord> getPrimaryKey() {
        return Keys.pk_IncidentNumbers;
    }

    @Override
    public IncidentNumbersTable as(String alias) {
        return new IncidentNumbersTable(DSL.name(alias), this);
    }

    @Override
    public IncidentNumbersTable as(Name alias) {
        return new IncidentNumbersTable(alias, this);
    }

    @Override
    public IncidentNumbersTable as(Table<?> alias) {
        return new IncidentNumbersTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IncidentNumbersTable rename(String name) {
        return new IncidentNumbersTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IncidentNumbersTable rename(Name name) {
        return new IncidentNumbersTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IncidentNumbersTable rename(Table<?> name) {
        return new IncidentNumbersTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IncidentNumbersTable where(Condition condition) {
        return new IncidentNumbersTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IncidentNumbersTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IncidentNumbersTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IncidentNumbersTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IncidentNumbersTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IncidentNumbersTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IncidentNumbersTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IncidentNumbersTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IncidentNumbersTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IncidentNumbersTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
