/*
 * This file is generated by jOOQ.
 */
package net.rupyber_studios.rupyber_database_api.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import net.rupyber_studios.rupyber_database_api.jooq.DefaultSchema;
import net.rupyber_studios.rupyber_database_api.jooq.Keys;
import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentsTable.Incidents;
import net.rupyber_studios.rupyber_database_api.jooq.tables.records.PrioritiesRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrioritiesTable extends TableImpl<PrioritiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Priorities</code>
     */
    public static final PrioritiesTable Priorities = new PrioritiesTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PrioritiesRecord> getRecordType() {
        return PrioritiesRecord.class;
    }

    /**
     * The column <code>Priorities.id</code>.
     */
    public final TableField<PrioritiesRecord, Integer> id = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Priorities.priority</code>.
     */
    public final TableField<PrioritiesRecord, String> priority = createField(DSL.name("priority"), SQLDataType.VARCHAR(8), this, "");

    /**
     * The column <code>Priorities.color</code>.
     */
    public final TableField<PrioritiesRecord, Integer> color = createField(DSL.name("color"), SQLDataType.INTEGER.nullable(false), this, "");

    private PrioritiesTable(Name alias, Table<PrioritiesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PrioritiesTable(Name alias, Table<PrioritiesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>Priorities</code> table reference
     */
    public PrioritiesTable(String alias) {
        this(DSL.name(alias), Priorities);
    }

    /**
     * Create an aliased <code>Priorities</code> table reference
     */
    public PrioritiesTable(Name alias) {
        this(alias, Priorities);
    }

    /**
     * Create a <code>Priorities</code> table reference
     */
    public PrioritiesTable() {
        this(DSL.name("Priorities"), null);
    }

    public <O extends Record> PrioritiesTable(Table<O> path, ForeignKey<O, PrioritiesRecord> childPath, InverseForeignKey<O, PrioritiesRecord> parentPath) {
        super(path, childPath, parentPath, Priorities);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class Priorities extends PrioritiesTable implements Path<PrioritiesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> Priorities(Table<O> path, ForeignKey<O, PrioritiesRecord> childPath, InverseForeignKey<O, PrioritiesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private Priorities(Name alias, Table<PrioritiesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public Priorities as(String alias) {
            return new Priorities(DSL.name(alias), this);
        }

        @Override
        public Priorities as(Name alias) {
            return new Priorities(alias, this);
        }

        @Override
        public Priorities as(Table<?> alias) {
            return new Priorities(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<PrioritiesRecord> getPrimaryKey() {
        return Keys.pk_Priorities;
    }

    @Override
    public List<UniqueKey<PrioritiesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.uk_Priorities_114129772);
    }

    private transient Incidents _incidents;

    /**
     * Get the implicit to-many join path to the <code>Incidents</code> table
     */
    public Incidents incidents() {
        if (_incidents == null)
            _incidents = new Incidents(this, null, Keys.fk_Incidents_pk_Priorities.getInverseKey());

        return _incidents;
    }

    @Override
    public PrioritiesTable as(String alias) {
        return new PrioritiesTable(DSL.name(alias), this);
    }

    @Override
    public PrioritiesTable as(Name alias) {
        return new PrioritiesTable(alias, this);
    }

    @Override
    public PrioritiesTable as(Table<?> alias) {
        return new PrioritiesTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PrioritiesTable rename(String name) {
        return new PrioritiesTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PrioritiesTable rename(Name name) {
        return new PrioritiesTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PrioritiesTable rename(Table<?> name) {
        return new PrioritiesTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PrioritiesTable where(Condition condition) {
        return new PrioritiesTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PrioritiesTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PrioritiesTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PrioritiesTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PrioritiesTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PrioritiesTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PrioritiesTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PrioritiesTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PrioritiesTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PrioritiesTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
