/*
 * This file is generated by jOOQ.
 */
package net.rupyber_studios.rupyber_database_api.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import net.rupyber_studios.rupyber_database_api.jooq.DefaultSchema;
import net.rupyber_studios.rupyber_database_api.jooq.Keys;
import net.rupyber_studios.rupyber_database_api.jooq.tables.IncidentsTable.Incidents;
import net.rupyber_studios.rupyber_database_api.jooq.tables.records.RecipientsRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipientsTable extends TableImpl<RecipientsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Recipients</code>
     */
    public static final RecipientsTable Recipients = new RecipientsTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RecipientsRecord> getRecordType() {
        return RecipientsRecord.class;
    }

    /**
     * The column <code>Recipients.id</code>.
     */
    public final TableField<RecipientsRecord, Integer> id = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Recipients.recipients</code>.
     */
    public final TableField<RecipientsRecord, String> recipients = createField(DSL.name("recipients"), SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>Recipients.color</code>.
     */
    public final TableField<RecipientsRecord, Integer> color = createField(DSL.name("color"), SQLDataType.INTEGER.nullable(false), this, "");

    private RecipientsTable(Name alias, Table<RecipientsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RecipientsTable(Name alias, Table<RecipientsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>Recipients</code> table reference
     */
    public RecipientsTable(String alias) {
        this(DSL.name(alias), Recipients);
    }

    /**
     * Create an aliased <code>Recipients</code> table reference
     */
    public RecipientsTable(Name alias) {
        this(alias, Recipients);
    }

    /**
     * Create a <code>Recipients</code> table reference
     */
    public RecipientsTable() {
        this(DSL.name("Recipients"), null);
    }

    public <O extends Record> RecipientsTable(Table<O> path, ForeignKey<O, RecipientsRecord> childPath, InverseForeignKey<O, RecipientsRecord> parentPath) {
        super(path, childPath, parentPath, Recipients);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class Recipients extends RecipientsTable implements Path<RecipientsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> Recipients(Table<O> path, ForeignKey<O, RecipientsRecord> childPath, InverseForeignKey<O, RecipientsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private Recipients(Name alias, Table<RecipientsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public Recipients as(String alias) {
            return new Recipients(DSL.name(alias), this);
        }

        @Override
        public Recipients as(Name alias) {
            return new Recipients(alias, this);
        }

        @Override
        public Recipients as(Table<?> alias) {
            return new Recipients(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<RecipientsRecord> getPrimaryKey() {
        return Keys.pk_Recipients;
    }

    @Override
    public List<UniqueKey<RecipientsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.uk_Recipients_129587470);
    }

    private transient Incidents _incidents;

    /**
     * Get the implicit to-many join path to the <code>Incidents</code> table
     */
    public Incidents incidents() {
        if (_incidents == null)
            _incidents = new Incidents(this, null, Keys.fk_Incidents_pk_Recipients.getInverseKey());

        return _incidents;
    }

    @Override
    public RecipientsTable as(String alias) {
        return new RecipientsTable(DSL.name(alias), this);
    }

    @Override
    public RecipientsTable as(Name alias) {
        return new RecipientsTable(alias, this);
    }

    @Override
    public RecipientsTable as(Table<?> alias) {
        return new RecipientsTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RecipientsTable rename(String name) {
        return new RecipientsTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RecipientsTable rename(Name name) {
        return new RecipientsTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RecipientsTable rename(Table<?> name) {
        return new RecipientsTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientsTable where(Condition condition) {
        return new RecipientsTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientsTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientsTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientsTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientsTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientsTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientsTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientsTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientsTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientsTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
